"""empty message

Revision ID: fd24e2a19698
Revises: 4f75fbcdaa48
Create Date: 2021-03-30 04:32:14.635710

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fd24e2a19698'
down_revision = '4f75fbcdaa48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('label', sa.String(length=250), nullable=False))
    op.drop_column('todo', 'label1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('label1', mysql.VARCHAR(length=250), nullable=False))
    op.drop_column('todo', 'label')
    # ### end Alembic commands ###
